/*
 * This file was automatically generated by Magic from servergardens.com
 */

export const environment = {
  production: false,

  // The URL to your backend API.
  apiUrl: 'http://localhost:55247/',

  // The domain for your backend API. Needed for "oauth0".
  apiDomain: 'localhost:55247',
};
